import moment from 'moment';

const kennyAge = moment().diff('2000-04-11', 'years');

const aboutMe = `Prazer meu nome é Kennedy, tenho ${kennyAge} anos  sou de São Matheus zona leste, sou Barbeiro, afro descendente.
A minha profissão de barbeiro  se desenvolveu ao meus 13 anos com meu pai e com os 17 anos tive um convite para trabalhar em um salão no centro de São Paulo, fundada por africanos, aceitei o convite  buscando minha independência profissional e tendo o público 90% afro, então me especializei em corte Afro com eles do salão chamado LeepJam e isso é o diferencial.
Venho de uma família humilde, Tenho uma história que foi difícil sobre essa sociedade que nos oprimi.
Eu agradeço a Deus por meus pais ser sido país novos e ser responsáveis ao ponto de não deixar faltar nada dentro de casa, hoje em dia já temos uma estabilidade bacana.
Cheguei a fazer cursos “ Manutenção de Aeronave e Engenharia Aeroespacial “ consegui terminar o básico, pois não consegui dar continuidade por serem bem longe da minha casa e do meu trabalho, meus pais tem as responsabilidades deles e eu tive as minhas assim que eu comecei a trabalhar, então realizei meus através de muito esforço e trabalho, pois o curso é caro e por passar o tempo na rua eu vivia cansado mentalmente e fisicamente, muito esforço que havia fazendo de “ segunda a sexta curso e trabalho  “ sábado eu só trabalhava.
Uma carreira muito independente (passagens de ônibus saia do meu dinheiro, o café da manhã, almoço e janta, Eu saia de casa as 5:00 e chegava em casa as 23:00, infelizmente eu não tive a estabilidade pra manter esse meu outro sonho, que é pilotar avião, ser mecânico de aeronaves, Sonho com isso!
Hoje eu trabalho como barbeiro, Sempre tive a certeza que se eu me dedicasse o sucesso viria.
O progresso foi chegando, fui pra um salão de médio padrão (barbearia marconi) em 27/09/2019 e lá as pessoas começou a reconhecer mais o meu trabalho, meu público é cabelo afro, e pela minha dedicação pessoas ao meu redor me dizia! ( kenny na minha quebrada os cara não manja corte afro por que você não dá o curso?
Eu pensei e hoje em dia estou preparando um curso que vai começar dia 04/10/2020, estou ansioso pra passar minha experiência a diante, chego a me emocionar pois muitas pessoas duvidava e ainda duvida que eu sou capaz de ser um educador Afro. E após isso quando eu criar minha estabilidade de morar sozinho ter minha vida independente, irei dar continuidade nos meus sonhos.
Fui convidado em 2022 para o salão @vizuhairclub é o salão que atuo hoje considerado o Maior salão com diversidade de cabelo e talentos com cabelos Crespos/Cacheados e ondulados.
Em 2022 tudo mudou, hoje tenho o meu reconhecimento internacional, cliente e alunos! Sou mentor de curso a 3 anos e me orgulho muito de ter transbordado experiência para muitas pessoas de São Paulo e para todas pessoas que trabalhou comigo.`;

export const tsTechnique = `Venho trazer pra vocês um pedacinho da minha história e de como essa técnica mudou a minha vida.
Eu corto cabelo desde os meus 13 anos de idade, aprendi com o meu pai que é barbeiro. Quando completei 16 anos de idade fui convidado a participar de uma equipe de barbeiros que fica localizado no centro de São Paulo, todos da barbearia eram senegaleses “africanos“. Trabalhei com eles durante três anos e como o público do salão era 85% composto por africanos, eu aprendi muito com eles e como lidar com cabelos crespos e cacheados, obtendo com o tempo o conhecimento do visagismo, que era sempre moldar o corte para encaixar em cada rosto e traços que era diferentes um dos outros e as curvaturas que também eram diferentes.
Até aí eu nunca havia cortado cabelo feminino, tinha uma moça que era apaixonada por cortes curtos e ela disse que eu tinha muito talento em cabelo masculino cacheado e crespo. Um dia ela chegou no salão pedindo pra que eu cortasse o cabelo dela e eu recusei a cortar o cabelo dela umas cinco vezes dizendo que eu não fazia cortes femininos.
Então eu parei e me questionei do por que eu estava dando aquela resposta, comecei a pensar que independente do gênero, se trata de afro estima e eu deveria entregar um bom trabalho para essas pessoas.
Na próxima vez que ela foi ao salão eu topei cortar o cabelo dela e ela me mostrou uma referência de um cabelo curto de origem
americana. Naquela época eu usava apenas tesoura reta, mas consegui realizar o corte, só que eu senti que deveria aperfeiçoar esse corte Tapered Cut. Após realizar o corte no cabelo dela, eu recebi muitos elogios, porém eu falei pra ela que não era pra contar pra ninguém porque eu não me sentia preparado para fazer em outras pessoas.

Passou cerca de um mês e comecei a receber clientes mulheres que pararam essa mesma cliente na rua pra perguntar onde ela cortou e ela ter me recomendado. A partir daí, eu só passei a aperfeiçoar cada vez mais, com mais ideias o Tapered Cut.
Conheci a tesoura curva com um homem do Afeganistão que vendia tesouras em barbearia, pensei que com os cabelos black power e o corte Tapered Cut faria muito sentido a ser feito com uma tesoura curva, para justamente trazer um corte mais arredondado, foi aí que eu comprei essa tesoura e comecei a conhecer ela e a forma com que se trabalha com ela.
No começo de 2020, comecei a receber muitas mensagens de pessoas querendo fazer curso comigo, pois o meu trabalho já estava começando a ter um alcance alto no Estados Unidos e no Brasil.
Eu percebi que eu precisava de um espaço mais bonito e com mais iluminação para que eu pudesse entregar postagens com mais qualidade visual. Então, me mudei para uma barbearia tradicional e quando eu cheguei tinha nove barbeiros todos os especializados em cabelos lisos e apenas um barbeiro especialista em cabelo afro.
Seis profissionais de outros salões entraram em contato comigo perguntando se eu dava curso e eu disse que não pois não sabia como ministrar um curso e se eu era apto para isso. Uma dessas profissionais que entrou em contato comigo falou "quando você estiver pronto entra em contato conosco porque estamos querendo muito aprender a técnica que você utiliza nesses cortes". Cerca de 3 meses se passaram e elas montaram um grupo e falaram "você já tem sua primeira turma, é só agendar a data e passar pra gente o valor do curso". Depois desse dia eu pensei que tudo tem sua hora e que tudo aconteceu no momento certo.
Agendei a data com elas e rolou o primeiro curso, teve muitos feedbacks positivos e teve apenas um negativo, que era "Kenny, você precisa de uma equipe, fica muito pesado fazer tudo sozinho".

Depois de ministrar alguns cursos, ensinando a vários alunos de diversas partes do Brasil a fora, fui aperfeiçoando a cada dia a didática e a minha Técnica TS.
Passei 3 anos nessa barbearia, onde todos os barbeiros que foram colegas de trabalho aprenderam esse corte TaperedCut comigo, deixei meu legado nessa barbearia e fiz com que o público afro ficasse cada vez maior e fico feliz por ter deixado esse meu legado.
Em fevereiro de 2022 resolvi ir para um salão de cabeleireiro, pois eu senti que o meu público feminino precisava de um ambiente em que se sentisse mais confortável e acolhido, já que na barbearia eu percebia que as minhas cliente se sentiam incomodadas com os assuntos dos barbeiros que estavam ao lado. Hoje atendo em uma sala exclusiva, pensando no conforto e bem estar dos meus clientes, além de possuir uma boa infraestrutura para ministrar meus cursos presenciais.`;

export default aboutMe;
